In [1]:
import numpy as np
import pandas as pd

In [2]:
dense_df=pd.read_csv("IMDB Dataset.csV")

In [3]:
dense_df.shape

(50000, 2)

In [4]:
df = dense_df.iloc[:10000]

In [5]:
df.shape

(10000, 2)

In [6]:
df.head

<bound method NDFrame.head of                                                  review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[10000 rows x 2 columns]>

In [8]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [10]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [12]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [13]:
df.duplicated().sum()

17

In [16]:
df.drop_duplicates(inplace=True)

C:\Users\fahad\AppData\Local\Temp\ipykernel_3336\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


## Preprocessing

In [18]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'),'',raw_text)
    return cleaned_text

In [19]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\fahad\AppData\Local\Temp\ipykernel_3336\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [22]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

In [31]:
df['review'] = df['review'].apply(lambda x:x.lower())

C:\Users\fahad\AppData\Local\Temp\ipykernel_3336\740760900.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [32]:
from nltk.corpus import stopwords 
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x: " " .join(x))

C:\Users\fahad\AppData\Local\Temp\ipykernel_3336\2898945066.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x: " " .join(x))


In [33]:
df['review'][0]

"one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. hardcore, classic use word.it called oz nickname given oswald maximum security state penitentary. focuses mainly emerald city, experimental section prison cells glass fronts face inwards, privacy high agenda. em city home many..aryans, muslims, gangstas, latinos, christians, italians, irish more....so scuffles, death stares, dodgy dealings shady agreements never far away.i would say main appeal show due fact goes shows dare. forget pretty pictures painted mainstream audiences, forget charm, forget romance...oz mess around. first episode ever saw struck nasty surreal, say ready it, watched more, developed taste oz, got accustomed high levels graphic violence. violence, injustice (crooked guards who'll sold nickel, inmates who'll kill order g

In [34]:
df.head()

review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. filming technique...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive

In [39]:
X = df.iloc[:,0:1]
Y = df['sentiment']

In [41]:
from sklearn.preprocessing import LabelEncoder 
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

In [42]:
Y

array([1, 1, 1, ..., 0, 0, 1])

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,Y,test_size=0.2, random_state=1)

In [45]:
X_train.shape

(7986, 1)

In [44]:
# Applying Bag of Words(BOW)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [54]:
X_train_bow =cv.fit_transform(X_train['review']).toarray()
X_test_bow =cv.transform(X_test['review']).toarray()

In [55]:
X_train_bow.shape


(7986, 48282)

In [56]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [57]:
X_test_bow.shape

(1997, 48282)

In [59]:
y_predict = gnb.predict(X_test_bow)
y_predict

array([1, 1, 0, ..., 1, 0, 0])

In [60]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_predict)

0.6324486730095142

In [61]:
confusion_matrix(y_test,y_predict)

array([[717, 235],
       [499, 546]], dtype=int64)

In [62]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_predict = rf.predict(X_test_bow)
accuracy_score(y_test,y_predict)

0.8482724086129194

In [64]:
cv = CountVectorizer(max_features=3000)
X_train_bow =cv.fit_transform(X_train['review']).toarray()
X_test_bow =cv.transform(X_test['review']).toarray()
gnb1 = GaussianNB()
gnb1.fit(X_train_bow,y_train)
y_predict1 = gnb1.predict(X_test_bow)
accuracy_score(y_test,y_predict1)

0.7896845267901853

In [70]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)
X_train_bow =cv.fit_transform(X_train['review']).toarray()
X_test_bow =cv.transform(X_test['review']).toarray()
gnb1 = GaussianNB()
gnb1.fit(X_train_bow,y_train)
y_predict1 = gnb1.predict(X_test_bow)
print("Naive bayes accuracy with BI grams = " ,accuracy_score(y_test,y_predict1))

Naive bayes accuracy with BI grams =  0.8117175763645468


In [72]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)
X_train_bow =cv.fit_transform(X_train['review']).toarray()
X_test_bow =cv.transform(X_test['review']).toarray()
rf3 = RandomForestClassifier()
rf3.fit(X_train_bow,y_train)
y_predict3 = rf.predict(X_test_bow)
print(" Random Forest Accuracy on Bi grams = ",accuracy_score(y_test,y_predict3))

 Random Forest Accuracy on Bi grams =  0.8477716574862293


In [71]:
cv = CountVectorizer(ngram_range=(1,3),max_features=5000)
X_train_bow =cv.fit_transform(X_train['review']).toarray()
X_test_bow =cv.transform(X_test['review']).toarray()
gnb2 = GaussianNB()
gnb2.fit(X_train_bow,y_train)
y_predict2 = gnb1.predict(X_test_bow)
print("Naive bayes accuracy with Tri grams = " ,accuracy_score(y_test,y_predict2))

Naive bayes accuracy with Tri grams =  0.556835252879319


In [74]:
cv = CountVectorizer(ngram_range=(1,3),max_features=5000)
X_train_bow =cv.fit_transform(X_train['review']).toarray()
X_test_bow =cv.transform(X_test['review']).toarray()
rf4 = RandomForestClassifier()
rf4.fit(X_train_bow,y_train)
y_predict4 = rf.predict(X_test_bow)
print(" Random Forest Accuracy on tri grams = ",accuracy_score(y_test,y_predict4))

 Random Forest Accuracy on tri grams =  0.6079118678017026


## Using TF-IDF

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [76]:
X_train_tfidf =tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf =tfidf.transform(X_test['review']).toarray()

In [77]:
rf5 = RandomForestClassifier()
rf5.fit(X_train_bow,y_train)
y_predict5 = rf.predict(X_test_bow)
print(" Random Forest Accuracy on TF-IDF = ",accuracy_score(y_test,y_predict5))

 Random Forest Accuracy on TF-IDF =  0.6079118678017026
